/*
 * This source file was generated by the Gradle 'init' task
 */
package itolliu.esstress.simulation;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;

import java.net.URI;
import java.net.http.HttpClient;
import java.util.concurrent.Executors;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        try (
                var http = buildHttpClient();
                var executor = Executors.newFixedThreadPool(10)
//                var executor = Executors.newSingleThreadExecutor()
        ) {
            var json = buildObjectMapper();
            var baseUrl = URI.create("http://localhost:8081");
            var client = new Client(http, json, baseUrl);

            var simulation = new Simulation(client, executor, 12, 10000);

            simulation.run();
            simulation.checkFinalBalances();
            simulation.checkRunningBalances();
        }
    }


    static HttpClient buildHttpClient() {
        return HttpClient.newBuilder().build();
    }

    static ObjectMapper buildObjectMapper() {
        var objectMapper = new ObjectMapper();
        objectMapper.registerModule(new JavaTimeModule());

        return objectMapper;
    }
}
