POST http://localhost:8081/accounts
Content-Type: application/json
Accept: application/json

{
  "amount": "100.00"
}

###

POST http://localhost:8081/accounts
Content-Type: application/json
Accept: application/json

{
  "amount": "120.00"
}

###