services:
  db:
    image: "postgres:17.5-alpine"
    restart: unless-stopped
    environment:
      POSTGRES_DB: regularsystem
      POSTGRES_USER: regularsystem
      POSTGRES_PASSWORD: regularsystem-password
    ports:
      - "5433:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U regularsystem"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  pgdata: